---

- name: "Start"
  hosts: localhost
  vars:
    Files: []
    Malware: []
  vars_files:
    - ./vars.yml
  connection: local 
  tasks:

  - name: Find exe files in ./malware
    ansible.builtin.find:
      paths: ./malware
      patterns: '*.exe'
    register: output

  - name: Adding Files to the list
    no_log: true
    set_fact:
      Files: "{{ Files + [item.path]}}" 
    with_items: "{{ output.files }}"

  - debug: var=Files

  - name: Append another item to the list
    set_fact:
      Malware: "{{ Malware + [item]  }}"
    with_random_choice: "{{ Files }}"


  - name: Copy files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: ./roles/send/malware/test.exe
    with_items: "{{ Malware }}"


- hosts: wc
  vars_files:
    - vars.yml
  roles:
      - send
  gather_facts: yes
