---

- name: Creating Temporary Directory
  win_file:
    path: 'C:\tmp\'
    state: directory


- name: Copy malware
  win_copy:
    src: ./roles/send/malware/test.exe
    dest: 'C:\tmp'


- name: PsExec
  win_copy:
    src: ./roles/send/dependencies/PsExec.exe
    dest: 'C:\tmp\PsExec.exe'
    force: no

- name: Run Windows Calculator
  win_command: 'C:\tmp\PsExec.exe -accepteula -nobanner -i 1 -s calc.exe'
  register: output
- debug: var=output